# Конфигурация сетевого сканера
# TCP сканирование
probe_timeout: 5
web_timeout: 10

# Веб-скриншоты
viewport_width: 1280
viewport_height: 720
max_browsers: 3

# Логирование
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file: "scanner.log"

# Пользовательские порты (опционально)
# ports_tcp_probe:
#   22: ""           # SSH
#   80: "HEAD / HTTP/1.0\r\n\r\n"
#   443: ""          # HTTPS
#   135: ""          # RPC
#   139: ""          # NetBIOS
#   445: ""          # SMB
#   3389: ""         # RDP
#   5985: ""         # WinRM HTTP
#   5986: ""         # WinRM HTTPS
#   1433: ""         # MSSQL
#   3306: ""         # MySQL
#   5432: ""         # PostgreSQL 