version: '3.8'

services:
  network-scanner:
    build: .
    container_name: network-scanner
    ports:
      - "5000:5000"
    volumes:
      # Mount directories for results
      - ./results:/app/results
      - ./logs:/app/logs
      - ./reports:/app/reports
      # Mount configuration (optional)
      - ./config.py:/app/config.py:ro
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
      - FLASK_APP=src.task_web
    restart: unless-stopped
    # Privileges for network scanning
    privileged: true
    # Network capabilities
    network_mode: host
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
    # Healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  results:
  logs:
  reports:
