version: '3.8'

services:
  network-scanner:
    image: andreis1s/net_scan:latest
    container_name: network-scanner
    ports:
      - "5000:5000"
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
    restart: unless-stopped
    privileged: true
    network_mode: host
